version: '2'
services:

  chinachu:
    build:
        context: chinachu
        args:
         - REPOSITORY=https://github.com/Chinachu/Chinachu.git
         - BRANCH=gamma
    container_name: chinachu
    ports:
     - "10772:10772"
     - "20772:20772"
     - "5353:5353/udp"
    network_mode: "host"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /data/chinachu/conf/config.json:/usr/local/chinachu/config.json
     - /data/chinachu/conf/rules.json:/usr/local/chinachu/rules.json
     - /data/chinachu/data:/usr/local/chinachu/data
     - /data/chinachu/recorded:/usr/local/chinachu/recorded
    restart: always
